[versions]
gg-jte="3.1.12"

[libraries]
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web" }
spring-boot-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
gg-jte-jte={module="gg.jte:jte", version.ref="gg-jte"}
gg-jte-spring-boot={module="gg.jte:jte-spring-boot-starter-3", version.ref="gg-jte"}
org-jspecify = { module = "org.jspecify:jspecify", version = "1.0.0" }

# code quality
palantir-javaformat = { module = "com.palantir.javaformat:palantir-java-format", version = "2.50.0" }

# gradle plugins
diffplug-spotless = { module = "com.diffplug.spotless:spotless-plugin-gradle", version = "6.25.0" }
#git-properties = { module = "com.gorylenko.gradle-git-properties:gradle-git-properties", version = "2.4.2" }
#sonarqube = { module = "org.sonarsource.scanner.gradle:sonarqube-gradle-plugin", version = "5.1.0.4882" }

[plugins]
gg-jte = { id = "gg.jte.gradle", version = "3.1.12" }
spring-boot = { id = "org.springframework.boot", version = "3.3.5" }
