spring:
  application:
    name: dictionary-learning-platform
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  threads:
    virtual:
      enabled: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: info,health,sbom
  info:
    git:
      mode: simple

server:
  error:
    whitelabel:
      enabled: false

gg:
  jte:
    development-mode: false
    use-precompiled-templates: true

logging:
  level:
    org:
      springframework:
        security: ERROR #change to DEBUG or INFO for more information about spring security

dictionary:
  service:
    page:
      size: 7
