# This workflow deploys application.
name: 02 - Deploy application

on:
  workflow_run:
    workflows:
      - '01 - Run application tests'
    types:
      - completed
    branches:
      - main

jobs:
  changes:
    name: Detect relevant source changes
    runs-on: ubuntu-24.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    outputs:
      app: ${{ steps.filter.outputs.app }}
      libs-versions: ${{ steps.filter.outputs.libs-versions }}
      dockerfile: ${{ steps.filter.outputs.dockerfile }}
      workflow-deploy: ${{ steps.filter.outputs.workflow-deploy }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Run changes detection
        uses: dorny/paths-filter@v3.0.2
        id: filter
        with:
          filters: |
            app:
              - 'app/src/main/**'
            libs-versions:
              - 'gradle/libs.versions.toml'
            dockerfile:
              - 'Dockerfile'
            workflow-deploy:
              - '.github/workflows/02-deploy-docker-image.yml'

  build-docker-image:
    name: Build and deploy the docker image
    needs: changes
    runs-on: ubuntu-24.04
    if: ${{ needs.changes.outputs.app == 'true' || needs.changes.outputs.libs-versions == 'true' || needs.changes.outputs.dockerfile == 'true' || needs.changes.outputs.workflow-deploy == 'true' }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64, amd64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build Docker image and push to Docker Hub
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64, linux/arm64
          push: true
          tags: |
            beo1975/dictionary-learning-platform:1.0.0
            beo1975/dictionary-learning-platform:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: DigitalOcean App Platform deployment
        uses: digitalocean/app_action@v2.0.8
        with:
          app_name: beo-1975-dictionary-learning-platform
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          images: '[
                  {
                    "name": "beo-1975-dictionary-learning-platform",
                    "image":{
                      "registry_type": "DOCKER_HUB",
                      "registry": "beo1975",
                      "repository": "dictionary-learning-platform",
                      "tag": "1.0.0"
                    }
                  }
                ]'

  scan-docker-image:
    name: Check Docker image for vulnerabilities
    runs-on: ubuntu-24.04
    permissions:
      security-events: write
    needs: build-docker-image
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Scan Docker image
        continue-on-error: true
        uses: snyk/actions/docker@master
        with:
          image: beo1975/dictionary-learning-platform:latest
          args: --file=Dockerfile --severity-threshold=high
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
